version: '3.8'

services:

  yamdb-db:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  yamdb-srv:
    image: vtlbz/api-yamdb:lastest
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - yamdb-db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.21.3-alpine
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certbot/conf/:/etc/letsencrypt/
      - ./nginx/certbot/www/:/var/www/certbot/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      - yamdb-srv

  certbot:
    image: certbot/certbot
    restart: always
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  pg_data:
  static_value:
  media_value:
